export type {
  ActivityEvent,
  AnalysisInput,
  Freshness,
  Highlight,
  HighlightType,
  Metric,
  OrganizationRef,
  Period,
  Person,
  Provider,
  ReportContext,
  ReportScopeType,
  Risk,
  ScopeRef,
  WorkItem,
  WorkItemStatus,
  WorkType,
} from "@teamtales/common/domain";
