import type { FormEvent, ReactElement } from "react";
import { useEffect, useState } from "react";
import type { DashboardDto, GitHubDiscoveryDto, LinearDiscoveryDto } from "@teamtales/common/api";
import type { Provider } from "@teamtales/common/domain";
import { apiClient } from "./api";
type Notice = { tone: "success" | "error" | "info"; text: string };

export function ProvidersSection({ dashboard, organizationId, onChanged, onError, onNotice }: { dashboard: DashboardDto | undefined; organizationId: string; onChanged: () => void; onError: (error: unknown) => void; onNotice: (notice: Notice) => void }): ReactElement {
  const [integrationId, setIntegrationId] = useState<string>(); const [provider, setProvider] = useState<Provider>("github"); const [token, setToken] = useState(""); const [displayName, setDisplayName] = useState(""); const [discovery, setDiscovery] = useState<GitHubDiscoveryDto | LinearDiscoveryDto>(); const [filter, setFilter] = useState(""); const [githubModes, setGithubModes] = useState<Map<string, "all" | "selected">>(new Map()); const [repositoryIds, setRepositoryIds] = useState<Set<string>>(new Set()); const [linearMode, setLinearMode] = useState<"all" | "selected">("all"); const [teamIds, setTeamIds] = useState<Set<string>>(new Set());
  const integration = dashboard?.integrations.find(item => item.id === integrationId);
  useEffect(() => { if (!integrationId) return; void (async () => { try { const response = await apiClient.listIntegrationResources(integrationId, organizationId); setDiscovery(response.discovery); const scopes = dashboard?.syncScopes.filter(scope => scope.integrationId === integrationId && scope.enabled) ?? []; if (response.provider === "github") { setGithubModes(new Map(scopes.filter(scope => scope.scopeType === "github.organization").map(scope => [scope.externalId, scope.selectionMode as "all" | "selected"]))); setRepositoryIds(new Set(scopes.filter(scope => scope.scopeType === "github.repository").map(scope => scope.externalId))); } else { const workspace = scopes.find(scope => scope.scopeType === "linear.workspace"); setLinearMode(workspace?.selectionMode === "selected" ? "selected" : "all"); setTeamIds(new Set(scopes.filter(scope => scope.scopeType === "linear.team").map(scope => scope.externalId))); } } catch (error) { onError(error); } })(); }, [dashboard?.syncScopes, integrationId, onError, organizationId]);
  async function connect(event: FormEvent<HTMLFormElement>): Promise<void> { event.preventDefault(); try { const result = await apiClient.addPatIntegration({ organizationId, provider, token, displayName: displayName || undefined }); setToken(""); setDisplayName(""); setIntegrationId(result.id); onChanged(); } catch (error) { onError(error); } }
  async function save(): Promise<void> { if (!integrationId || !discovery) return; try { if (integration?.provider === "github" && "organizations" in discovery) { await apiClient.setSyncScopeSelection(integrationId, { organizationId, selection: { organizations: [...githubModes].map(([organizationId, mode]) => mode === "all" ? { organizationId, mode } : { organizationId, mode, repositoryIds: discovery.repositories.filter(repo => repo.organizationId === organizationId && repositoryIds.has(repo.id)).map(repo => repo.id) }), repositoryIds: discovery.repositories.filter(repo => !repo.organizationId && repositoryIds.has(repo.id)).map(repo => repo.id) } }); } else if ("workspace" in discovery) await apiClient.setSyncScopeSelection(integrationId, { organizationId, selection: linearMode === "all" ? { mode: "all" } : { mode: "selected", teamIds: [...teamIds] } }); onChanged(); onNotice({ tone: "success", text: "Provider scopes saved." }); setIntegrationId(undefined); } catch (error) { onError(error); } }
  const toggle = (id: string, values: Set<string>, set: (value: Set<string>) => void) => { const next = new Set(values); next.has(id) ? next.delete(id) : next.add(id); set(next); };
  if (integrationId && discovery) return <div className="grid"><section className="panel"><h2>Configure scopes{integration ? `: ${integration.displayName}` : ""}</h2><label>Search<input value={filter} onChange={event => setFilter(event.target.value)} /></label>{"organizations" in discovery ? <><h3>Organizations</h3>{discovery.organizations.map(org => <fieldset key={org.id}><legend>{org.name ?? org.login}</legend><label><input type="radio" checked={githubModes.get(org.id) === "all"} onChange={() => setGithubModes(current => new Map(current).set(org.id, "all"))} />All repositories</label><label><input type="radio" checked={githubModes.get(org.id) === "selected"} onChange={() => setGithubModes(current => new Map(current).set(org.id, "selected"))} />Selected repositories</label>{githubModes.get(org.id) === "selected" && discovery.repositories.filter(repo => repo.organizationId === org.id && repo.fullName.toLowerCase().includes(filter.toLowerCase())).map(repo => <label className="check-row" key={repo.id}><input type="checkbox" checked={repositoryIds.has(repo.id)} onChange={() => toggle(repo.id, repositoryIds, setRepositoryIds)} />{repo.fullName}</label>)}</fieldset>)}<h3>Other repositories</h3>{discovery.repositories.filter(repo => !repo.organizationId && repo.fullName.toLowerCase().includes(filter.toLowerCase())).map(repo => <label className="check-row" key={repo.id}><input type="checkbox" checked={repositoryIds.has(repo.id)} onChange={() => toggle(repo.id, repositoryIds, setRepositoryIds)} />{repo.fullName}</label>)}</> : <><label><input type="radio" checked={linearMode === "all"} onChange={() => setLinearMode("all")} />All teams</label><label><input type="radio" checked={linearMode === "selected"} onChange={() => setLinearMode("selected")} />Selected teams</label>{linearMode === "selected" && discovery.teams.filter(team => `${team.name} ${team.key}`.toLowerCase().includes(filter.toLowerCase())).map(team => <label className="check-row" key={team.id}><input type="checkbox" checked={teamIds.has(team.id)} onChange={() => toggle(team.id, teamIds, setTeamIds)} />{team.name} ({team.key})</label>)}</>}<button type="button" onClick={() => void save()}>Save scopes</button> <button type="button" onClick={() => setIntegrationId(undefined)}>Cancel</button></section></div>;
  const integrations = dashboard?.integrations ?? []; return <div className="grid two"><section className="panel"><h2>Connect provider</h2><form className="form-grid" onSubmit={event => void connect(event)}><label>Provider<select value={provider} onChange={event => setProvider(event.target.value as Provider)}><option value="github">GitHub</option><option value="linear">Linear</option></select></label><label>Token<input type="password" required value={token} onChange={event => setToken(event.target.value)} /></label><label>Display name (optional)<input value={displayName} onChange={event => setDisplayName(event.target.value)} /></label><p>{provider === "github" ? "GitHub token needs repository and organization access." : "Create a personal API key in Linear Settings > API."}</p><button disabled={!organizationId}>Connect and configure scopes</button></form></section><section className="panel"><h2>Integrations</h2>{integrations.length === 0 ? <p>No integrations.</p> : integrations.map(item => <div className="meta-row" key={item.id}><strong>{item.provider} / {item.displayName}</strong><button type="button" onClick={() => setIntegrationId(item.id)}>Edit scopes</button></div>)}</section></div>;
}
